version: '3.7' # specify docker-compose version

services:
  mongo:
    image: mongo:4.0
    restart: always
    ports:
    - "27017:27017"
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
      POSTGRES_USER: user
    volumes:
    - ./postgres/data:/var/lib/postgresql
    - ./postgres/pg-initdb.d:/docker-entrypoint-initdb.d